# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6c9925b10475d40f6b2f05ff139718493c09d6c817a0fada4029a87ac230805a5cab0a8420b3edf7d64325eff0d6d5df9bcb3182ac7246d36a8ad8e8fc021ae

test:
  secret_key_base: bed7c1309727278927469a046a490ae708e51f2ad455e510df43a09e539ba62d559380412c0964c0bcb4d147f7bd3fbf94015db6c15b5e47a38cd5a6b4b66f4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
